### PR TITLE
Add support for Angular v12

### LINKED ISSUE #131: Support Angular v12
See https://blog.angular.io/angular-v12-is-now-available-32ed51fbfd49 for more info

### PR DESCRIPTION
**Pull request by icepeng**
* update angular-devkit dependencies
* use "$id" instead of deprecated "id" for schema

resolve #131

### CODE REVIEW

**Comment by fmalcher** [comment]
Thank you for your contribution! ❤️ LGTM at first sight.

**Comment by JohannesHoppe** [comment]
@icepeng Many thanks for your support. 😃 👍 

I published `angular-cli-ghpages@1.0.0-rc.2` to npm. Please test it all and let me know if it works for you.

**Comment by JohannesHoppe** [comment]
I had no error on my machine but our build produced a couple of mom warnings?! 

https://github.com/angular-schule/angular-cli-ghpages/actions/runs/887731643

**Comment by icepeng** [comment]
Seems like Github Actions node version issue. Latest Angular CLI requires a minimum Node.js version of either v12.14 or v14.15.

**Comment by JohannesHoppe** [comment]
@icepeng You were right, the node version was just too old:
https://github.com/angular-schule/angular-cli-ghpages/commit/2576a32aefca23cc8032870edc98d5e66f8adbf6

Now everything is green again! Thanks again for your contribution! 👍

**Pull request merged**
